#!/usr/bin/env python3
"""Configuration for all sites. Auto-generated by gen_config.py"""
# Generated: 2026-08-31 11:01:03

BASE_SETTINGS = {
  "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
  "timeout": 30,
  "max_retries": 3,
  "max_articles_per_site": 500
}

SITES = {
  "phayul_bo": {"name": "Phayul Tibetan", "base_url": "https://phayul.com/bo/", "strategy": "rss", "delay": 2.0, "feed_url": "https://phayul.com/bo/feed/", "content_selectors": [".entry-content", "article"]},
  "phayul": {"name": "Phayul", "base_url": "https://phayul.com", "strategy": "rss", "delay": 2.0, "feed_url": "https://phayul.com/feed/", "content_selectors": [".entry-content", "article"]},
  "tibetpost_bo": {"name": "Tibet Post Tibetan", "base_url": "https://www.thetibetpost.com/bo", "strategy": "html", "delay": 2.0, "content_selectors": [".article-content-main", "article"]},
  "tibetpost": {"name": "Tibet Post", "base_url": "https://www.thetibetpost.com", "strategy": "html", "delay": 2.0, "content_selectors": [".article-content-main", "article"]},
  "dalailamaworld": {"name": "Dalai Lama World", "base_url": "http://www.dalailamaworld.com", "strategy": "wayback", "delay": 3.0, "content_selectors": ["#content", ".content"]},
  "xizangzhiye_bo": {"name": "Xizang Zhiye Tibetan", "base_url": "https://xizang-zhiye.org/bo/", "strategy": "wayback", "delay": 3.0, "content_selectors": ["#content", ".content", ".entry-content", "article"]},
  "xizangzhiye": {"name": "Xizang Zhiye", "base_url": "https://xizang-zhiye.org", "strategy": "wayback", "delay": 3.0, "content_selectors": ["#content", ".content", ".entry-content", "article"]},
  "vot_bo": {"name": "VOT Tibetan", "base_url": "https://www.vot.org/", "strategy": "playwright", "delay": 3.0, "content_selectors": [".entry-content", "article", ".content"]},
  "vot": {"name": "VOT Chinese", "base_url": "https://www.vot.org/cn/", "strategy": "playwright", "delay": 3.0, "content_selectors": [".entry-content", "article", ".content"]},
  "tibetnet_bo": {"name": "Tibet.net Tibetan", "base_url": "https://tibet.net/bo/", "strategy": "rss", "delay": 3.0, "feed_url": "https://tibet.net/bo/feed/", "content_selectors": [".entry-content", "article"]},
  "tibetnet": {"name": "Tibet.net", "base_url": "https://tibet.net", "strategy": "rss", "delay": 3.0, "feed_url": "https://tibet.net/feed/", "content_selectors": [".entry-content", "article"]},
  "tibetanparliament": {"name": "Tibetan Parliament", "base_url": "https://tibetanparliament.org", "strategy": "wayback", "delay": 3.0, "content_selectors": ["#content", ".content", ".entry-content", "article"]},
  "tibetexpress": {"name": "Tibet Express", "base_url": "http://www.tibetexpress.net", "strategy": "wayback", "delay": 3.0, "content_selectors": ["#content", ".content", ".entry-content", "article"]},
  "sfft": {"name": "Students for Afree Tibetan", "base_url": "https://studentsforafreetibet.org", "strategy": "rss", "delay": 2.0, "feed_url": "https://studentsforafreetibet.org/feed", "content_selectors": [".entry-content", "article"]},
  "savetibet": {"name": "Save Tibetan", "base_url": "https://www.savetibet.org", "strategy": "rss", "delay": 2.0, "feed_url": "https://www.savetibet.org/feed", "content_selectors": [".entry-content", "article"]},
  "freetibet": {"name": "Free Tibet", "base_url": "https://freetibet.org", "strategy": "html", "delay": 2.0, "content_selectors": [".article-content-main", "article"]},
  "tibetreview": {"name": "Tibetan Review", "base_url": "https://www.tibetanreview.net", "strategy": "rss", "delay": 2.0, "feed_url": "https://www.tibetanreview.net/feed", "content_selectors": [".td-post-content", ".tdb_single_content"]},
  "tibettruth": {"name": "Tibetan Truth", "base_url": "https://tibettruth.com", "strategy": "rss", "delay": 2.0, "feed_url": "https://tibettruth.com/feed", "content_selectors": [".entry-content", "article"]},
  "tchrd": {"name": "Tibetan Centre for Human Rights and Democracy", "base_url": "http://tchrd.org", "strategy": "rss", "delay": 2.0, "feed_url": "http://tchrd.org/feed", "content_selectors": [".td-post-content", ".tdb_single_content"]},
  "tibetinformation": {"name": "Tibetan Information Office", "base_url": "http://tibetoffice.com.au", "strategy": "rss", "delay": 2.0, "feed_url": "http://tibetoffice.com.au/feed", "content_selectors": [".main-content", ".entry-content"]},
  "tibetoffice": {"name": "The office of Tibetan", "base_url": "http://tibetoffice.org", "strategy": "rss", "delay": 2.0, "feed_url": "http://tibetoffice.org/feed", "content_selectors": [".entry", ".post-inner"]},
  "sherig": {"name": "Department of education", "base_url": "https://sherig.org", "strategy": "rss", "delay": 2.0, "feed_url": "https://sherig.org/?feed=rss2", "content_selectors": [".w-post-elm.post_content", ".post_content"]},
  "indiatibet": {"name": "India Tibet Coordination office", "base_url": "https://www.indiatibet.net", "strategy": "rss", "delay": 2.0, "feed_url": "https://www.indiatibet.net/feed", "content_selectors": [".entry-content", "article"]},
  "nalanda": {"name": "Buddhist News Nalanda", "base_url": "https://nalanda.news/", "strategy": "rss", "delay": 2.0, "feed_url": "https://nalanda.news/rssdzen.xml", "content_selectors": [".entry-content", "article"]},
  "tibethouse_jp": {"name": "Tibet House Japan", "base_url": "https://www.tibethouse.jp/", "strategy": "rss", "delay": 2.0, "feed_url": "https://www.tibethouse.jp/feed", "content_selectors": [".entry-content", "article"]},
  "tibetbureau": {"name": "Bureau of His Holiness The Dalai Lama", "base_url": "https://tibetbureau.in/", "strategy": "rss", "delay": 2.0, "feed_url": "https://tibetbureau.in/feed", "content_selectors": [".entry-content", "article"]},
  "officeoftibet": {"name": "Office of Tibet Pretoria", "base_url": "https://officeoftibet.com/", "strategy": "rss", "delay": 2.0, "feed_url": "https://officeoftibet.com/feed", "content_selectors": [".article-contents", "article"]},
  "tibetinf_au": {"name": "Tibetan Information Office,Australia", "base_url": "http://tibetoffice.com.au/", "strategy": "rss", "delay": 2.0, "feed_url": "http://tibetoffice.com.au/feed", "content_selectors": [".entry-content", "article"]},
  "tibetgeneva": {"name": "The Tibet Bureau Geneva", "base_url": "https://www.tibetoffice.ch/", "strategy": "rss", "delay": 2.0, "feed_url": "https://www.tibetoffice.ch/feed", "content_selectors": [".entry-content", "article"]},
}
