#!/usr/bin/env python3
"""Generate config.py - run this to regenerate."""

import json
from datetime import datetime

# 源数据：每个元组 = (site_key, site_name, base_url, strategy, delay, feed_url)
S = [
    ("phayul_bo", "Phayul Tibetan", "https://phayul.com/bo/", "rss", 2.0, "https://phayul.com/bo/feed/"),
    ("phayul", "Phayul", "https://phayul.com", "rss", 2.0, "https://phayul.com/feed/"),
    ("tibetpost_bo", "Tibet Post Tibetan", "https://www.thetibetpost.com/bo", "html", 2.0, None),
    ("tibetpost", "Tibet Post", "https://www.thetibetpost.com", "html", 2.0, None),
    ("dalailamaworld", "Dalai Lama World", "http://www.dalailamaworld.com", "wayback", 3.0, None),
    ("xizangzhiye_bo", "Xizang Zhiye Tibetan", "https://xizang-zhiye.org/bo/", "wayback", 3.0, None),
    ("xizangzhiye", "Xizang Zhiye", "https://xizang-zhiye.org", "wayback", 3.0, None),
    ("vot_bo", "VOT Tibetan", "https://www.vot.org/", "playwright", 3.0, None),
    ("vot", "VOT Chinese", "https://www.vot.org/cn/", "playwright", 3.0, None),
    ("tibetnet_bo", "Tibet.net Tibetan", "https://tibet.net/bo/", "rss", 3.0, "https://tibet.net/bo/feed/"),
    ("tibetnet", "Tibet.net", "https://tibet.net", "rss", 3.0, "https://tibet.net/feed/"),
    ("tibetanparliament", "Tibetan Parliament", "https://tibetanparliament.org", "wayback", 3.0, None),
    ("tibetexpress", "Tibet Express", "http://www.tibetexpress.net", "wayback", 3.0, None),
    ("sfft", "Students for Afree Tibetan", "https://studentsforafreetibet.org", "rss", 2.0,
     "https://studentsforafreetibet.org/feed"),
    ("savetibet", "Save Tibetan", "https://www.savetibet.org", "rss", 2.0, "https://www.savetibet.org/feed"),
    ("","","https://www.tibetsun.com",)
]

# 为不同策略配置默认的 content_selectors
DEFAULT_SELECTORS = {
    "rss": [".entry-content", "article"],
    "html": ["article", ".post-content", ".entry-content", ".content"],
    "wayback": ["#content", ".content", ".entry-content", "article"],
    "playwright": [".entry-content", "article", ".content"],
}

# 特定站点的定制选择器（覆盖默认值）
CUSTOM_SELECTORS = {
    "tibetpost_bo": [".article-content-main", "article"],
    "tibetpost": [".article-content-main", "article"],
    "dalailamaworld": ["#content", ".content"],
}


def generate_config():
    """生成 config.py 文件"""

    sites = {}

    for key, name, base_url, strategy, delay, feed_url in S:
        # 基础配置
        site_config = {
            "name": name,
            "base_url": base_url,
            "strategy": strategy,
            "delay": delay,
        }

        # 添加 feed_url（仅 RSS 策略需要）
        if strategy == "rss" and feed_url:
            site_config["feed_url"] = feed_url

        # 添加 content_selectors
        if key in CUSTOM_SELECTORS:
            site_config["content_selectors"] = CUSTOM_SELECTORS[key]
        elif strategy in DEFAULT_SELECTORS:
            site_config["content_selectors"] = DEFAULT_SELECTORS[strategy]
        else:
            site_config["content_selectors"] = ["article", ".content"]

        sites[key] = site_config

    base_settings = {
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        "timeout": 30,
        "max_retries": 3,
        "max_articles_per_site": 500,
    }

    # 写入 config.py
    with open("config.py", "w", encoding="utf-8") as f:
        f.write('#!/usr/bin/env python3\n')
        f.write('"""Configuration for all sites. Auto-generated by gen_config.py"""\n')
        f.write(f'# Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n\n')

        # 写入 BASE_SETTINGS
        f.write("BASE_SETTINGS = ")
        f.write(json.dumps(base_settings, ensure_ascii=False, indent=2))
        f.write("\n\n")

        # 写入 SITES：每个 site 配置单独占一行
        f.write("SITES = {\n")
        for k, v in sites.items():
            f.write(f'  "{k}": {json.dumps(v, ensure_ascii=False)},\n')
        f.write("}\n")

    print(f"✅ config.py generated successfully with {len(sites)} sites")


if __name__ == "__main__":
    generate_config()